[build-system]
build-backend = "poetry.core.masonry.api"
requires = ["poetry-core>=1.0.0"]

[tool]
[tool.poetry]
authors = ["Ginger Industries"]
description = ""
name = "etchlang"
version = "0.1.0"
[tool.poetry.dependencies]
python = "^3.8"
sly = "^0.4"
requests = "^2.27.1"
toml = "^0.10.2"
[tool.poetry.dev-dependencies]
